# Redirect all www traffic to non-www (Primary domain is sondermomentsphotography.com)
[[redirects]]
from = "https://www.sondermomentsphotography.com/*"
to = "https://sondermomentsphotography.com/:splat"
status = 301
force = true

# Redirect Finnish users to /fi/
[[redirects]]
from = "/"
to = "/fi/"
status = 301
force = true
conditions = { Country = ["FI"] }

# Redirect everyone else to /en/
[[redirects]]
from = "/"
to = "/en/"
status = 301
force = true
conditions = { Country = [] }

# Fix CORS issue for site.webmanifest
[[headers]]
for = "/site.webmanifest"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "application/manifest+json"
